#!/bin/bash
 
xsetroot -cursor_name left_ptr
sxhkd &
 
bspc config border_width	2
bspc config window_gap		20
 
bspc config split_ratio		0.62
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod1
 
bspc config automatic_scheme	spiral

# workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

bspc rule -a Chromium desktop='^2'
bspc rule -a Gimp desktop='^8' state=floating follow=on

# AutoStart
feh --bg-fill Pictures/Wallpapers/4647404.png
picom -b
$HOME/.config/polybar/launch.sh
xinput set-prop "GXT7863:00 27C6:01E0 Touchpad" "libinput Tapping Enabled" 1
